
/*---------------------------------------------------------------------------------------------------------------------------------------
Load the main model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
model moes.mod;
data moes.dat;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load building 1 data
---------------------------------------------------------------------------------------------------------------------------------------*/
#data moesb1.dat;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load building 2 data
---------------------------------------------------------------------------------------------------------------------------------------*/
#data moesb2.dat;

/*---------------------------------------------------------------------------------------------------------------------------------------
Load building data
---------------------------------------------------------------------------------------------------------------------------------------*/
data moesbBC.dat;
data moesbCO.dat;
data moesbBP.dat;
data moesbBS.dat;
data moesbTCV.dat;
data moesbIN.dat;
data moesbGC.dat;
data moesbCE.dat;
data moesbODY.dat;
data moesbMA.dat;
data moesbGR.dat;
data moesbME.dat;
data moesbCM.dat;
data moesbAA.dat;
data moesbBI.dat;
data moesbEL.dat;
data moesbPO.dat;
data moesbCRPP.dat;
data moesbMX.dat;
data moesbBM.dat;
data moesbCH.dat;
data moesbDIA.dat;
data moesbPH.dat;
data moesbAI.dat;



/*---------------------------------------------------------------------------------------------------------------------------------------
Load the utilities model and its data
---------------------------------------------------------------------------------------------------------------------------------------*/
model moesboiler.mod;
data moesboiler.dat;

model moesPV.mod;
data moesPV.dat;

model moesCogenerationEngine.mod;
data moesCogenerationEngine.dat;

model moesSOFC.mod;
data moesSOFC.dat;

model moesHP2stage.mod;
data moesHP2stage.dat;

#When HP1Stage included costs = 0
model moesHP1stageLT.mod;
data moesHP1stageLT.dat;

model moesHP1stageMT.mod;
data moesHP1stageMT.dat;





/*---------------------------------------------------------------------------------------------------------------------------------------
Set the grid parameters: resource flow and fmax
---------------------------------------------------------------------------------------------------------------------------------------*/
let  Flowout['Natgas','NatGasGrid'] := refSize;
let  Fmax['NatGasGrid'] := refSize;
let  Flowout['Electricity','ElecGridBuy'] := refSize;
let  Fmax['ElecGridBuy'] := refSize;
let  Flowin['Electricity','ElecGridSell'] := refSize;
let  Fmax['ElecGridSell'] := refSize;


/*---------------------------------------------------------------------------------------------------------------------------------------
AMPL options
---------------------------------------------------------------------------------------------------------------------------------------*/
option solver 'cplex';											# choose the solver
option omit_zero_rows 1;										# to not display 0 in rows
option omit_zero_cols 1;										# to not display 0 in columns

/*---------------------------------------------------------------------------------------------------------------------------------------
Solve the problem
---------------------------------------------------------------------------------------------------------------------------------------*/
solve;

/*---------------------------------------------------------------------------------------------------------------------------------------
Display commands
---------------------------------------------------------------------------------------------------------------------------------------*/
display Edemand;
display Qheating;
display Qheatingdemand;

display mult;
display mult_t;

display Flowin;
display Flowout;

display FlowInUnit;
display FlowOutUnit;

display Buildings;

#display usedroofArea;

display InvCost;

display OpCost;

display use;

display COP_HP1stageLT;
display COP_HP1stageMT;
